apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample-app-1
    version: "1"
  name: sample-app-1
  namespace: my-component-1
spec:
  containers:
  - image: alpine
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    name: sample-app-1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: 
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
  dnsPolicy: ClusterFirst
  restartPolicy: Always
